<?php

declare(strict_types=1);

namespace App\GraphQL;

class HippoGraphQLErrorCodes
{
	const CREDIT_CARD_AMOUNT_DUE_EXCEEDED = 100;

	const ACCOUNT_CREDIT_ISSUE_BALANCE_IS_POSITIVE = 200;
	const DISPENSE_CHANGE_BALANCE_IS_POSITIVE = 201;
	const ACCOUNT_CREDIT_NOT_SELECTED = 202;

	const INVOICE_VOID_PAYMENTS_EXIST = 300;
	const INVOICE_ADD_ITEM_EXCEEDS_INVENTORY = 301;
	const INVOICE_ITEM_INVENTORY_NOT_FOUND = 302;
	const INVOICE_ADD_ITEM_INVALID_INVOICE_STATUS = 303;
	const INVOICE_UPDATE_CANNOT_BE_ESTIMATE = 304;
	const INVOICE_COMPLETE_MISSING_SERIAL = 305;
	const INVOICE_ADD_ITEM_MISSING_PROVIDER = 306;
	const INVOICE_SET_ACTIVE_ON_COMPLETED = 307;
	const INVOICE_REOPEN_ON_OPEN = 308;
	const INVOICE_ADD_ITEM_INVALID_QUANTITY = 309;
	const INVOICE_ADD_ITEM_SPECIES_RESTRICTED = 310;

	const RECEIVING_COMPLETE_NO_SUPPLIER = 400;
	const RECEIVING_NOT_OPEN = 401;

	const NON_POSITIVE_PAYMENT_AMOUNT = 500;
	const REFUND_MULTIPLE_INVOICES = 501;

	const CLEARENT_TERMINAL_NOT_CONFIGURED = 510;

	// User
	const USER_NOT_PROVIDER = 600;

	// Vaccination
	const VACCINE_ON_COMPLETED_INVOICE = 700;
	const VACCINE_NOT_PROVIDED = 701;
	const VACCINE_CHANGE_ON_COMPLETED_INVOICE = 702;
	const VACCINE_CHANGE_ON_ITEM_KIT = 703;
	const VACCINE_INVOICE_INVALID = 704;
	const VACCINE_LOCATION_REQUIRED_FOR_INVOICE = 705;
}
